name: README build
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *"  # Fixed cron syntax (was "0 4 * **")
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push changes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}  # Use your PAT for checkout

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Updated Python version

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Create cache directory
        run: mkdir -p cache

      - name: Run update script
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: python today.py

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions-bot@lost-saint.github.io"
          git config --global user.name "Lost-Saint/GitHub-Actions-Bot"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Updated README [automated]"
            git push
          fi
